"""Create GitHub Issues from scan findings."""

from __future__ import annotations

import logging
from datetime import datetime, timezone

import httpx

from backend.config import GitHubConnection, TaskAction, TaskConfig

logger = logging.getLogger(__name__)


async def create(
    task: TaskConfig,
    run_id: str,
    findings: list[dict],
    conn: GitHubConnection,
    action: TaskAction,
) -> bool:
    """Create a GitHub Issue summarising scan findings."""
    if not findings or not conn.token:
        return False

    title = f"[{task.name}] {len(findings)} finding(s) — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
    body = _format_issue_body(task, run_id, findings)

    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {conn.token}",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    payload: dict = {
        "title": title,
        "body": body,
    }
    if action.labels:
        payload["labels"] = action.labels
    if action.assign:
        payload["assignees"] = [action.assign]

    async with httpx.AsyncClient() as client:
        try:
            resp = await client.post(
                f"https://api.github.com/repos/{conn.owner}/{conn.repo}/issues",
                headers=headers,
                json=payload,
                timeout=15.0,
            )
            resp.raise_for_status()
            issue = resp.json()
            logger.info(f"Created issue #{issue.get('number')} for task {task.id}")
            return True
        except Exception as e:
            logger.error(f"Failed to create GitHub issue: {e}")
            return False


def _format_issue_body(task: TaskConfig, run_id: str, findings: list[dict]) -> str:
    """Format findings as GitHub-flavoured Markdown."""
    lines = [
        f"## Scan Report: {task.name}",
        "",
        f"- **Run ID**: `{run_id}`",
        f"- **Type**: {task.scan.type}",
        f"- **Mode**: {task.scan.mode}",
        f"- **Findings**: {len(findings)}",
        "",
    ]

    # Summary table
    severity_counts: dict[str, int] = {}
    for f in findings:
        sev = f.get("severity", "medium")
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    lines.append("### Severity Breakdown")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in ["critical", "high", "medium", "low", "info"]:
        if sev in severity_counts:
            lines.append(f"| {sev.capitalize()} | {severity_counts[sev]} |")
    lines.append("")

    # Findings detail (limit to 20 to avoid huge issues)
    lines.append("### Findings")
    shown = findings[:20]
    for f in shown:
        sev = f.get("severity", "medium")
        emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵", "info": "⚪"}.get(sev, "⚪")
        lines.append(f"- {emoji} **{f.get('description', '')}**")
        lines.append(f"  `{f.get('file_path', '')}:{f.get('line_number', 0)}`")
        if f.get("context"):
            ctx = f["context"][:150].replace("`", "\\`")
            lines.append(f"  > {ctx}")
        lines.append("")

    if len(findings) > 20:
        lines.append(f"*... and {len(findings) - 20} more findings.*")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by Flexi Repo Scanner*")

    return "\n".join(lines)
